// <auto-generated />
using System;
using Mercado1.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mercado1.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mercado1.Api.Models.CarritoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carrito");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id_C")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_C"));

                    b.Property<string>("Codigo_C")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_C")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_C");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Mercado1.Api.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id_DP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_DP"));

                    b.Property<int>("Cantidad_DP")
                        .HasColumnType("int");

                    b.Property<string>("Codigo_DP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_P")
                        .HasColumnType("int");

                    b.Property<int>("Id_PE")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario_DP")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_DP");

                    b.HasIndex("Id_P");

                    b.HasIndex("Id_PE");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("Mercado1.Api.Models.EstadoPedido", b =>
                {
                    b.Property<int>("Id_E")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_E"));

                    b.Property<string>("Nombre_E")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_E");

                    b.ToTable("EstadosPedido");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Pedido", b =>
                {
                    b.Property<int>("Id_PE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_PE"));

                    b.Property<string>("Codigo_PE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionEnvio_PE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_PE")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_E")
                        .HasColumnType("int");

                    b.Property<int>("Id_U")
                        .HasColumnType("int");

                    b.HasKey("Id_PE");

                    b.HasIndex("Id_E");

                    b.HasIndex("Id_U");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id_P")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_P"));

                    b.Property<string>("Codigo_P")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion_P")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_C")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl_P")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_P")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio_P")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock_P")
                        .HasColumnType("int");

                    b.HasKey("Id_P");

                    b.HasIndex("Id_C");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Promocion", b =>
                {
                    b.Property<int>("Id_PR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_PR"));

                    b.Property<bool>("Activo_PR")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo_PR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin_PR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio_PR")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_P")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl_PR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoId_P")
                        .HasColumnType("int");

                    b.Property<string>("Titulo_PR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_PR");

                    b.HasIndex("ProductoId_P");

                    b.ToTable("Promociones");
                });

            modelBuilder.Entity("Mercado1.Api.Models.PromocionUsuario", b =>
                {
                    b.Property<int>("Id_PU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_PU"));

                    b.Property<DateTime>("FechaUso")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_PE")
                        .HasColumnType("int");

                    b.Property<int>("Id_PR")
                        .HasColumnType("int");

                    b.Property<int>("Id_U")
                        .HasColumnType("int");

                    b.HasKey("Id_PU");

                    b.HasIndex("Id_PE");

                    b.HasIndex("Id_PR");

                    b.HasIndex("Id_U");

                    b.ToTable("PromocionesUsuarios");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Resena", b =>
                {
                    b.Property<int>("Id_R")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_R"));

                    b.Property<int>("Calificacion_R")
                        .HasColumnType("int");

                    b.Property<string>("Codigo_R")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentario_R")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_R")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_P")
                        .HasColumnType("int");

                    b.Property<int>("Id_U")
                        .HasColumnType("int");

                    b.HasKey("Id_R");

                    b.HasIndex("Id_P");

                    b.HasIndex("Id_U");

                    b.ToTable("Resenas");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id_U")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_U"));

                    b.Property<string>("Codigo_U")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo_U")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre_U")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash_U")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt_U")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol_U")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_U");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Mercado1.Api.Models.DetallePedido", b =>
                {
                    b.HasOne("Mercado1.Api.Models.Producto", "Producto")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("Id_P")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercado1.Api.Models.Pedido", "Pedido")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("Id_PE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Pedido", b =>
                {
                    b.HasOne("Mercado1.Api.Models.EstadoPedido", "Estado")
                        .WithMany("Pedidos")
                        .HasForeignKey("Id_E")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercado1.Api.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("Id_U")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Producto", b =>
                {
                    b.HasOne("Mercado1.Api.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Id_C");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Promocion", b =>
                {
                    b.HasOne("Mercado1.Api.Models.Producto", "Producto")
                        .WithMany("Promociones")
                        .HasForeignKey("ProductoId_P")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Mercado1.Api.Models.PromocionUsuario", b =>
                {
                    b.HasOne("Mercado1.Api.Models.Pedido", "Pedido")
                        .WithMany("PromocionesUsuarios")
                        .HasForeignKey("Id_PE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercado1.Api.Models.Promocion", "Promocion")
                        .WithMany("PromocionesUsuarios")
                        .HasForeignKey("Id_PR")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercado1.Api.Models.Usuario", "Usuario")
                        .WithMany("PromocionesUsuarios")
                        .HasForeignKey("Id_U")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Promocion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Resena", b =>
                {
                    b.HasOne("Mercado1.Api.Models.Producto", "Producto")
                        .WithMany("Resenas")
                        .HasForeignKey("Id_P")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercado1.Api.Models.Usuario", "Usuario")
                        .WithMany("Resenas")
                        .HasForeignKey("Id_U")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Mercado1.Api.Models.EstadoPedido", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Pedido", b =>
                {
                    b.Navigation("DetallesPedido");

                    b.Navigation("PromocionesUsuarios");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Producto", b =>
                {
                    b.Navigation("DetallesPedido");

                    b.Navigation("Promociones");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Promocion", b =>
                {
                    b.Navigation("PromocionesUsuarios");
                });

            modelBuilder.Entity("Mercado1.Api.Models.Usuario", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("PromocionesUsuarios");

                    b.Navigation("Resenas");
                });
#pragma warning restore 612, 618
        }
    }
}
